# Configuration for aggregation of simple sector versions based on 
# Canada's Energy Future data

# Must be in ascending order along with all data in tables!
model_periods:
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050

sqlite_schema: "canoe_dataset_schema.sql"
sqlite_database: "cef.sqlite"

# Switches
force_wipe_database: true
build_test_model: false
use_dsd: false

# Which CEF scenario to pull data for
# "Current Measures", "Canada Net-zero", or "Global Net-zero"
scenario: "Global Net-zero"
data_id_prefix: "GNZ" # should resemble the scenario
data_version: "001"

cef_reference: "Government of Canada, C. E. R. (2023, August 16). CER - Canadas Energy Future 2023: Energy Supply and Demand Projections to 2050. https://www.cer-rec.gc.ca/en/data-analysis/canada-energy-future/2023/"

energy_units: "PJ"
conversion_factor: 1
decimal_places: 2
prop_thresh: 0.02 # Fuel proportions below this become zero